library(arules)
library(arulesViz)
library(dplyr)
data(Groceries)
Groceries
class(Groceries)
summary(Groceries)
head(size(Groceries))
inspect(Groceries[1:5])
length(which(duplicated(Groceries)))
head(itemFrequency(Groceries))
itemFrequencyPlot(Groceries, topN = 5)
itemFrequencyPlot(Groceries, support = 0.1)
fsets <- apriori(Groceries, parameter = list(supp = 0.01, target = "frequent itemsets"))
class(fsets)
inspect(sort(fsets)[1:5])
fsets[is.closed(fsets)]
fsets[is.maximal(fsets)]
rules <- apriori(Groceries)
rules <- apriori(Groceries, parameter = list(supp = 0.01, conf = 0.5))
rules <- apriori(Groceries, parameter = list(supp = 0.01, conf = 0.25))
summary(rules)
inspect(rules[1:5])
rules.sub <- subset(rules, subset = lift > 2)
inspect(rules.sub[1:5])
rules.sub <- subset(rules, subset = rhs %in% c("yogurt", "whole milk") & lift > 2)
rules.sort <- sort(rules.sub, by = "lift")
inspect(rules.sort[1:5])
plot(rules.sub)
plot(rules.sub, method = "graph")